name: Generated readme check

on:
  push:
    branches: [ master ]
    paths: 
      - 'README.md'
      - 'README.tpl'
      - 'lib.rs'
  pull_request:
    types: [ opened, edited ]
    branches: [ master ]
    paths: 
      - 'README.md'
      - 'README.tpl'
      - 'src/lib.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-readme
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-readme
        use-tool-cache: true
    - name: Check that readme is up-to-date
      run: '[[ ! $(cargo readme --template README.tpl | diff - README.md) ]]'
